name: Deploy Docusaurus Site

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    env:
      GIT_USER: ${{ github.actor }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: docs/node_modules
          key: ${{ runner.os }}-docs-${{ hashFiles('docs/package-lock.json') }}
          restore-keys: ${{ runner.os }}-docs-

      - name: Instalar dependências
        working-directory: docs
        run: npm ci

      # (Opcional) Testes
      # - name: Test
      #   working-directory: docs
      #   run: npm test

      - name: Build Docusaurus
        working-directory: docs
        run: npm run build

      - name: Deploy
        working-directory: docs
        run: npx docusaurus deploy
